version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: fiap-database
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fiap-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: fiap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fiap-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fiap-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://mysql:3306/mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret
    env_file:
      - .env
    networks:
      - fiap-network

  app-dev:
    build: .
    container_name: fiap-dev-app
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=jdbc:mysql://mysql:3306/mydatabase
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret
    env_file:
      - .env
    networks:
      - fiap-network

volumes:
  mysql_data:
  redis_data:

networks:
  fiap-network:
    driver: bridge